Repository alkemyTech/OT102-Server, pull requests merged in 2021-11, with the labels that each got.

#20 [ENDPOINT] GET /news/:id OT102-48
  controllers/entry.js
  routes/entries.js
  routes/index.js
  services/entryById.js
Labels: endpoint

#18 [ENDPOINT] DELETE /users/:id - OT102-44
  controllers/users.js
  routes/user.js
  services/user.js
Labels: endpoint

#21 [ENDPOINT]: GET /members - OT102-89
  controllers/members.js
  routes/index.js
  routes/members.js
  services/members.js
  test/members.test.js
Labels: endpoint

#19 [ENDPOINT] GET /contacts - OT102-73
  controllers/contacts.js
  routes/contacts.js
  routes/index.js
  services/contacts.js
Labels: endpoint

#24 [ENDPOINT] GET /organizations/1/public OT102-12 - v4
  controllers/organizationsController.js
  routes/index.js
  routes/organizations.js
  services/organizationServices.js
Labels: endpoint

#23 [ENDPOINT] GET / news / OT102-45
  controllers/entry.js
  package-lock.json
  routes/entries.js
  routes/index.js
  services/entry.js
Labels: endpoint

#26 [ENDPOINT] DELETE /categories/:id - OT102-99
  controllers/categories.js
  routes/categories.js
  services/categories.js
Labels: endpoint

#27 [ORGANIZATION] add columns migrations-seeders
  migrations/20211126160026-add-columns-to-Organization.js
  models/organization.js
  seeders/20211126162715-demo-organizations.js
Labels: fix

#37 Ot102 97 fix
  app.js
  controllers/categories.js
  controllers/users.js
  middlewares/error-handler.js
  middlewares/index.js
  services/user.js
Labels: fix

#25 [MIDDLEWARE] isAdmin -OT102-52
  config/config.js
  middlewares/isAdmin.js
  package.json
Labels: feature

#34 [ENDPOINT]: POST /categories - OT102-97
  controllers/categories.js
  helpers/error.js
  middlewares/error-handler.js
  middlewares/index.js
  routes/categories.js
  schemas/categories.js
  services/categories.js
Labels: endpoint

#35 [ENDPOINT]: GET /testimonials - OT102-121
  controllers/testimonials.js
  models/testimonial.js
  routes/index.js
  routes/testimonials.js
  services/testimonials.js
Labels: endpoint

#29 [ENDPOINT] PUT /testimonials/:id - OT102-85
  controllers/testimonials.js
  package-lock.json
  routes/testimonials.js
  services/testimonials.js
Labels: endpoint

#40 [ENDPOINT]: PUT /categories - OT102-98
  controllers/categories.js
  routes/categories.js
  services/categories.js
Labels: endpoint

#36 [ENDPOINT]: POST /members - OT102-90
  controllers/members.js
  models/member.js
  routes/members.js
  schemas/members.js
  services/members.js
Labels: endpoint

#33 [ENDPOINT] DELETE /news/:id - OT102-63
  controllers/entry.js
  routes/entries.js
  services/entry.js
Labels: endpoint

#39 [ENDPOINT] DELETE /members/:id - OT102-92
  controllers/members.js
  routes/members.js
  services/members.js
Labels: endpoint

#38 [ENDPOINT] POST /auth/register - OT102-32
  controllers/members.js
  controllers/users.js
  package-lock.json
  package.json
  routes/auth.js
  routes/index.js
  routes/members.js
  schemas/users.js
  services/members.js
  services/user.js
Labels: endpoint

#43 [ENDPOINT] DELETE /testimonials/:id - OT102-86
  controllers/testimonials.js
  routes/testimonials.js
  services/testimonials.js
Labels: endpoint

#42 [ENDPOINT] add isAdmin middleware - OT102-97-FIX
  routes/categories.js
Labels: fix

#41 [ENDPOINT] add isAdmin middleware - OT102-89-FIX
  routes/members.js
  test/members.test.js
Labels: fix

#45 [ENDPOINT] ADD-LIST-DETAIL-DELETE /activities - OT102-66
  controllers/activities.js
  routes/activities.js
  routes/index.js
  schemas/activities.js
  services/activities.js
Labels: endpoint

#44 [ENDPOINT] PUT /member/:id - OT102-91
  controllers/members.js
  routes/members.js
  services/members.js
Labels: endpoint

#48 [ENDOPOINT] GET /contacts - OT102-73 [FIX]
  controllers/contacts.js
  routes/contacts.js
Labels: fix
