Repository alkemyTech/OT102-Server, pull requests merged in 2021-12, with the labels that each got.

#50 [ENDPOINT] DELETE categories/:id OT102-99 [FIX]
  controllers/members.js
  routes/categories.js
  routes/members.js
Labels: fix

#47 [ENDPOINT] POST testimonials/ - OT102-84
  controllers/testimonials.js
  package-lock.json
  routes/testimonials.js
  schemas/testimonials.js
  services/testimonials.js
Labels: endpoint

#52 [ENDPOINT] UPDATE/activities - OT102 - 67
  controllers/activities.js
  routes/activities.js
  services/activities.js
Labels: endpoint

#46 [ENDPOINT] POST / contacts Ot102-72
  controllers/contacts.js
  routes/contacts.js
  routes/index.js
  schemas/contacs.js
  services/contacts.js
Labels: endpoint

#53 [ENDPOINT] PUT /news/:id OT102-56
  controllers/entry.js
  package-lock.json
  routes/entries.js
  schemas/entries.js
  services/entry.js
Labels: endpoint

#51 [ENDPOINT] GET /categories - OT102-96 / FIX
  controllers/categories.js
  routes/categories.js
Labels: fix

#49 [ENDPOINT] POST /auth/login OT102-25
  controllers/users.js
  middlewares/jwt.js
  routes/auth.js
  schemas/users.js
  services/user.js
Labels: endpoint

#57 [MIDDLEWARE] JWT logic OT102-33
  middlewares/auth.js
  middlewares/jwt.js
Labels: feature

#56 [ENDPOINT] Activities [FIX]
  controllers/activities.js
  routes/activities.js
  services/activities.js
Labels: fix

#58 [ENDPOINT] - POST /news - OT102-55
  controllers/entry.js
  routes/entries.js
  schemas/entries.js
  services/entry.js
Labels: endpoint

#59 [ENDPOINT] - GET organizations/:id/public - OT102-79
  controllers/organizationsController.js
Labels: endpoint

#60 Ot102 55 - FIX
  services/entry.js
Labels: fix

#61 [ENDPOINT] Get /categories/:id OT102-126
  controllers/categories.js
  routes/categories.js
  services/categories.js
Labels: endpoint

#65 [FIX] [ENDPOINT] /GET auth/me OT102-65-FIX
  controllers/users.js
  middlewares/userExtractor.js
  services/user.js
Labels: fix

#64 [FIX] fix adduser endpoint - OT102-65-FIX
  controllers/users.js
  services/roles.js
  services/user.js
Labels: fix

#63 [ENDPOINT] ACTIVITY - Get by id FIX
  controllers/activities.js
Labels: fix

#68 [FIX] [ENDPOINT] Fixed update entry service and controller - OT102-56
  controllers/entry.js
  services/entry.js
Labels: fix

#67 [ENPOINT] Testimonial MVC FIX
  controllers/testimonials.js
  routes/testimonials.js
  services/testimonials.js
Labels: fix

#69 [ENDPOINT] add slides route, controller and service - OT102-37
  controllers/organizationsController.js
  controllers/slides.js
  middlewares/isAdmin.js
  routes/index.js
  routes/members.js
  routes/slides.js
  schemas/slides.js
  services/slides.js
Labels: endpoint

#71 [ENDPOINT] [FIX] add missing organization PUT endpoint - OT102-37 FIX
  controllers/organizationsController.js
  controllers/slides.js
  routes/organizations.js
  services/organizationServices.js
  services/slides.js
Labels: fix, endpoint

#72 [TESTS] ENDPOINTS /testimonials - OT102-120
  services/testimonials.js
  test/testimonials.test.js
Labels: TEST

#73 [TESTING] add testing suites - OT102-114
  controllers/members.js
  services/members.js
  test/members.test.js
Labels: TEST
