Repository alkemyTech/OT102-Server, pull requests merged in 2022-01, with the labels that each got.

#77 [FIX] Edit seeders
  seeders/20201109013159-create-demo-user.js
  seeders/20211126162715-demo-organizations.js
  seeders/20211221191925-create-slides.js
Labels: fix

#76 [TEST] ENPOINT NEWS - OT102-116
  controllers/entry.js
  services/entry.js
  test/entries.test.js
Labels: TEST

#80 [ENDPOINT] Get user by id (FIX)
  controllers/users.js
  routes/user.js
  services/roles.js
  services/user.js
Labels: fix, endpoint

#78 [TEST] [FIX] Minor fixes to testimonials.test - Ot102 120(fix)
  services/testimonials.js
  test/testimonials.test.js
Labels: fix, TEST

#81 [ENDPOINT] Login (fix)
  controllers/users.js
Labels: fix, endpoint

#82 [FIX] - Fixes varios - OT102
  middlewares/userExtractor.js
  test/members.test.js
Labels: fix

#83 [FIX] seeds - new link with optimized images
  seeders/20211123062651-create-activities.js
  seeders/20211221161250-create-entries.js
Labels: fix
